version: '3.8'

services:

  web:
    image: drorganvidez/flask_base:latest
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: production
    depends_on:
      - db
    restart: always

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf
      - ./letsencrypt:/etc/letsencrypt:ro
      - ./public:/var/www:rw
    ports:
      - "80:80"
      - "443:443"
    restart: always

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --interval 120 flask_base-web-1
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./public:/var/www:rw
      - ./letsencrypt:/etc/letsencrypt

volumes:
  db_data:
