"""empty message

Revision ID: 7d71f2506fb0
Revises: fc92ca5970a4
Create Date: 2023-11-13 12:42:56.261048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d71f2506fb0'
down_revision = 'fc92ca5970a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_token', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token_request', schema=None) as batch_op:
        batch_op.drop_column('num_token')

    # ### end Alembic commands ###
