"""empty message

Revision ID: 7ec1d089de06
Revises: d86092c2df49
Create Date: 2023-11-12 11:38:26.926160

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7ec1d089de06'
down_revision = 'd86092c2df49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('votation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state_votation', sa.Enum('ACCEPTED', 'REJECTED', 'IN_PROGRESS', name='statevotation'), nullable=False))
        batch_op.add_column(sa.Column('proposal_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'proposal', ['proposal_id'], ['id'])
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('votation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', mysql.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('proposal_id')
        batch_op.drop_column('state_votation')

    # ### end Alembic commands ###
