"""empty message

Revision ID: e831043b1cf2
Revises: 3f0d903c3675
Create Date: 2023-11-11 16:39:51.265140

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e831043b1cf2'
down_revision = '3f0d903c3675'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proposal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=300), nullable=False))
        batch_op.add_column(sa.Column('subject', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('proposal_type', sa.Enum('TALK', 'ACTIVITY', 'STAND', name='proposaltype'), nullable=False))
        batch_op.add_column(sa.Column('state', sa.Enum('PENDING_OF_ADMISION', 'PENDING_OF_ACEPTATION', 'ON_PREPARATION', 'CONFIRMATED', 'REJECTED', 'CLOSED', name='state'), nullable=False))
        batch_op.add_column(sa.Column('innosoft_day_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'innosoft_day', ['innosoft_day_id'], ['id'])
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proposal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('innosoft_day_id')
        batch_op.drop_column('state')
        batch_op.drop_column('proposal_type')
        batch_op.drop_column('subject')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
