name: Selenium Tests

on:
  push:
    branches:
      - main
      - develop
      - api-test

jobs:
  deploy_infrastructure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and start infrastructure
        run: |
          docker-compose -f docker-compose.dev.yml up -d 

      - name: Run selenium container
        run: |
          docker run -d -p 4444:4444 --name selenium-container selenium/standalone-chrome

  run_selenium_tests:
    runs-on: ubuntu-latest

    needs: deploy_infrastructure

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install pytest
          pip install selenium==4.9.0

      - name: Run Selenium tests
        run: |
          pytest app/tests/selenium/test_selenium.py
